language: ruby
branches:
  only:
    - main
    - /^deploy-.*$/
cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database nawara_api_test;' -U postgres
  - bundle install --jobs=3 --retry=3
test:
  adapter: postgresql
  database: nawara_api_test
