language: ruby
branches:
  only:
    - main
    - /^deploy-.*$/
cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database nawara_api_test;' -U postgres
  - bundle install --jobs=3 --retry=3
test:
  adapter: postgresql
  database: nawara_api_test
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'